version: "3.4"

services:
  supchecker:
    build:
      context: ./
      target: builder
    image: supchecker-dev:latest
    volumes:
      - ./app:/app # Mount source code inside the container.
    working_dir: /app
    command: ["go", "run", "main.go"]